In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [3]:
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [5]:
a3.shape,a3.ndim,a3.dtype,a3.size,type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
import pandas as pd

In [7]:
data_frame = pd.DataFrame(a2)
data_frame

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [8]:
only_ones = np.ones((10,2))
only_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
only_zeroes = np.zeros((7,2,3))
only_zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
range_new = np.arange(0,100,3)
range_new

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
random_new2 = np.random.randint(0,10,(7,2))
random_new2

array([[0, 3],
       [5, 4],
       [1, 7],
       [6, 6],
       [9, 9],
       [6, 1],
       [3, 1]])

In [12]:
random_new3 = np.random.random((3,5))
random_new3

array([[0.21341154, 0.25306133, 0.78433586, 0.44986164, 0.7347966 ],
       [0.96215079, 0.4616007 , 0.55606541, 0.43138439, 0.95269448],
       [0.91009463, 0.7418557 , 0.77284445, 0.14989514, 0.06801984]])

In [13]:
np.random.seed(42)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [14]:
latest = np.random.randint(0,10,(3,7))
np.unique(latest)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [15]:
latest[0]

array([8, 0, 9, 2, 6, 3, 8])

In [16]:
latest[:2]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [17]:
latest[:2,:2]

array([[8, 0],
       [2, 4]])

In [18]:
tmp1 = np.random.randint(0,10,(3,5))
tmp_ones = np.ones((3,5))
tmp1+tmp_ones

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [19]:
tmp1_ones = np.ones((5,3))
tmp1_ones+tmp1.T

array([[ 5.,  3.,  4.],
       [ 2.,  1.,  2.],
       [ 4.,  4.,  6.],
       [ 7.,  2.,  6.],
       [ 8.,  8., 10.]])

In [20]:
np.square(tmp1)

array([[16,  1,  9, 36, 49],
       [ 4,  0,  9,  1, 49],
       [ 9,  1, 25, 25, 81]], dtype=int32)

In [21]:
np.std(tmp1)

2.5612496949731396

In [22]:
np.var(tmp1)

6.5600000000000005

In [26]:
np.reshape(tmp1,(5,3,1))

array([[[4],
        [1],
        [3]],

       [[6],
        [7],
        [2]],

       [[0],
        [3],
        [1]],

       [[7],
        [3],
        [1]],

       [[5],
        [5],
        [9]]])

In [32]:
tmp1 >= tmp1_ones.T

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [47]:
np.argmax(tmp1[1]),tmp1[1]

(4, array([2, 0, 3, 1, 7]))

In [49]:
np.argmax(tmp1,axis=1)

array([4, 4, 4], dtype=int64)

In [52]:
np.random.randn(2,10)

array([[-0.46146572,  0.06665728, -0.17628566,  1.20089277,  0.69839894,
        -0.17162884, -0.90718658,  1.18862573,  0.78553212,  2.65601009],
       [ 0.26348604,  1.64177112,  0.4608163 ,  0.08592347, -1.50995728,
         0.72150246, -0.84341992, -0.51332541, -0.0435368 , -0.27530091]])

In [53]:
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])