### Multi class classification model

In [1]:
import pandas as pd
import numpy as np

In [14]:
#importing data
wine = pd.read_csv('Data/winequality-white.csv')
wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        6  
1         9.5        6  
2        10.1        6  
3         9.9        6  
4         9.9        6  
...       ...      ...  
4893     11.2        6  
4894      9.6        5  
4895      9.4        6  
4896     12.8        7  
4897     11.8        6  

[4898 rows x 12 columns]

In [15]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

#split data
x = wine.drop('quality',axis = 1)
y = wine['quality']


In [16]:
#split into train and test
from sklearn.model_selection import train_test_split
x_train ,x_test, y_train , y_test = train_test_split(x,y, test_size = 0.2)

#train and test
clf.fit(x_train,y_train)
clf.score(x_test,y_test)

0.6755102040816326

In [52]:
np.array(y_test)
y_pred = clf.predict_proba(x_test)
y_pred[:10], np.array(y_test)[:10]

(array([[0.  , 0.  , 0.01, 0.  , 0.01, 0.98, 0.  ],
        [0.  , 0.  , 0.07, 0.17, 0.73, 0.03, 0.  ],
        [0.  , 0.  , 0.08, 0.68, 0.11, 0.13, 0.  ],
        [0.02, 0.17, 0.48, 0.28, 0.03, 0.02, 0.  ],
        [0.  , 0.03, 0.29, 0.36, 0.25, 0.06, 0.01],
        [0.  , 0.01, 0.29, 0.65, 0.03, 0.02, 0.  ],
        [0.  , 0.03, 0.38, 0.53, 0.06, 0.  , 0.  ],
        [0.  , 0.04, 0.14, 0.41, 0.3 , 0.11, 0.  ],
        [0.01, 0.04, 0.54, 0.32, 0.07, 0.02, 0.  ],
        [0.  , 0.01, 0.39, 0.51, 0.08, 0.01, 0.  ]]),
 array([8, 7, 6, 6, 6, 6, 5, 6, 6, 7], dtype=int64))

In [55]:
np.array(y_pred[:5,1:3])

array([[0.  , 0.01],
       [0.  , 0.07],
       [0.  , 0.08],
       [0.17, 0.48],
       [0.03, 0.29]])